[general]
import = []
working_directory = "None"
live_config_reload = true
ipc_socket = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 12, y = 12 }
dynamic_padding = false
decorations = "Full"
opacity = 0.98
blur = true
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"
resize_increments = true
option_as_alt = "OnlyLeft"
level = "Normal"

[scrolling]
history = 10000
multiplier = 4

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.25
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
line_indicator = { foreground = "None", background = "None" }
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.primary]
foreground = "#cdd6f4"
background = "#1e1e2e"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[bell]
animation = "Linear"
duration = 0
color = "#ac4242"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true
thickness = 0.3

[terminal]
# shell = { program = "/bin/zsh", args = ["-l"] }
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[hints]
alphabet = "jfkdls;ahgurieowpq"

# [[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
# hyperlinks = true
# post_processing = true
# persist = false
# mouse.enabled = true
# binding = { key = "O", mods = "Control|Shift" }
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = []

[debug]
render_timer = false
persistent_logging = false
log_level = "Error"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
