theme = "catppuccin_mocha"

[editor]
true-color = true

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
display-inlay-hints = true

[keys.insert]
"j" = { "k" = "normal_mode" }
