" https://github.com/junegunn/vim-plug/wiki/tips
" https://www.reddit.com/r/vim/comments/7datnj/comment/dpxfjym/?st=ja3oaqh0&sh=a9e76b40
" https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation
" https://github.com/skywind3000/vim-init
" https://github.com/wklken/k-vim
" https://github.com/amix/vimrc
" https://gitee.com/mirrorvim/vim-fast/blob/master/vimrc-no-plug
" https://github.com/chenxuan520/vim-fast
" https://github.com/liuchengxu/space-vim

scriptencoding=utf-8

" GUI:
if has('gui')
  set guioptions=
  if has('unix')
    set guifont=JetBrainsMono\ Nerd\ Font:h12
  elseif has('mac')
    set guifont=Menlo:h12
  elseif has('win32') || has('win64')
    set guifont=Consolas:h11
  endif
endif

" OPTIONS:
filetype plugin on
filetype indent on
syntax enable
syntax on
set autoread
set backspace=indent,eol,start
set ruler
set number
set relativenumber
set showmode
set cursorline
set colorcolumn=80
set clipboard^=unnamed,unnamedplus
set nowrap
set showtabline=2
set laststatus=2
set wildmenu
set wildmode=longest:full,full
set autoindent
set cindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set timeoutlen=500
set ttimeoutlen=500

" THEME:
set termguicolors
set background=dark
if v:version>=900
  set wildoptions=pum,fuzzy
  colorscheme retrobox
else
  colorscheme desert
endif

" BUILTIN_PLUGINS:
let g:loaded_2html_plugin = 1
let g:loaded_getscript = 1
let g:loaded_gzip = 1
let g:loaded_logipat = 1
let g:loaded_man = 1
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:loaded_netrwSettings = 1
let g:loaded_netrwFileHandlers = 1
let g:loaded_rrhelper = 1
let g:loaded_spellfile_plugin = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_2html_plugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_vimball = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1
let mapleader = ' '
let maplocalleader = ','

" KEYMAPPING:
nnoremap <Leader>cr :source $MYVIMRC<CR>
nnoremap <Leader>ce :edit $MYVIMRC<CR>
inoremap jk <ESC>
vnoremap jk <ESC>
cnoremap jk <C-c>
inoremap <C-a> <HOME>
vnoremap <C-a> <HOME>
cnoremap <C-a> <HOME>
inoremap <C-e> <END>
vnoremap <C-e> <END>
cnoremap <C-e> <END>
nnoremap <C-j> <C-w>j
nnoremap <C-h> <C-w>h
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" AUTOCMD:
augroup restore_cursor_position
  autocmd!
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line('$')
        \| execute "normal! g'\""
        \| endif
augroup end

augroup large_file_optimization
  autocmd!
  autocmd BufWinEnter * if getfsize(expand('%')) > 1048576
        \| syntax clear
        \| endif
augroup end

augroup disable_auto_comment
  autocmd!
  autocmd InsertEnter * setlocal formatoptions-=cro
augroup end

augroup language_tab_space_adjust
  autocmd!
  autocmd FileType python,json,jsonc setlocal shiftwidth=4 tabstop=4 softtabstop=4
augroup end

augroup close_with_q
  autocmd!
  autocmd FileType help,startuptime,man,lspinfo,quickfix,fugitive,fugitiveblame,checkhealth nnoremap <buffer><silent> q :close<cr>
augroup end

augroup language_comment_style
  autocmd!
  autocmd FileType c,cpp setlocal commentstring=//\ %s
  autocmd FileType markdown setlocal wrap
  autocmd FileType qf setlocal nonumber
augroup end

augroup performance_optimize
  autocmd!
  autocmd FileType * syntax sync minlines=200
augroup end

" VIM_PLUGINS:
nnoremap <Leader>tP :PlugStatus<cr>

let data_dir = has('win32') || has('win64') ? '$HOME/vimfiles' : '~/.config/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  if has('win32') || has('win64')
    silent execute '!powershell -Command "New-Item -Path "' . data_dir . ' -Name autoload -Type Directory -Force; Invoke-WebRequest -Uri https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -OutFile '.data_dir.'\autoload\plug.vim"'
  else
    silent execute '!curl -fLo ' . data_dir . '/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  endif
  augroup install_plugins_automatically
    autocmd vimenter * PlugInstall --sync
          \| source $MYVIMRC
  augroup END
endif

augroup install_plugin_when_startup
  autocmd!
  autocmd vimenter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
        \| PlugInstall --sync
        \| q
        \| endif
augroup end

call plug#begin(data_dir . '/plugged')

Plug 'ryanoasis/vim-devicons', { 'on': [] }
augroup load_vim_devicons
  autocmd!
  autocmd BufWinEnter,BufReadPost * call plug#load('vim-devicons')
        \| autocmd! load_vim_devicons
        \| let g:webdevicons_enable = 1
        \| let g:webdevicons_enable_startify = 1
        \| let g:webdevicons_enable_nerdtree = 1
augroup end

Plug 'mhinz/vim-startify', { 'on': [] }
augroup load_vim_startify
  autocmd!
  autocmd BufWinEnter * call plug#load('vim-startify')
        \| autocmd! load_vim_startify
        \| let g:startify_custom_header = []
        \| let g:startify_files_number = 15
        \| let g:startify_padding_left = winwidth(0) / 3
augroup end

Plug 'morhetz/gruvbox', { 'on': [] }
augroup load_gruvbox
  autocmd!
  autocmd BufReadPost * call plug#load('gruvbox')
        \| autocmd! load_gruvbox
        \| let g:gruvbox_contrast_dark = 'hard'
        \| colorscheme gruvbox
augroup end

Plug 'ap/vim-buftabline', { 'on': [] }
augroup load_vim_buftabline
  autocmd!
  autocmd BufReadPost * call plug#load('vim-buftabline')
        \| autocmd! load_vim_buftabline
augroup end

Plug 'Yggdroot/indentLine', { 'on': [] }
augroup load_indentline
  autocmd!
  autocmd BufReadPost * call plug#load('indentLine')
        \| autocmd! load_indentline
        \| let g:indentLine_char_list = ['│']
        \| IndentLinesEnable
augroup end

Plug 'itchyny/lightline.vim', { 'on': [] }
Plug 'shinchu/lightline-gruvbox.vim', { 'on': [] }
augroup load_lightline
  autocmd!
  autocmd BufReadPost * call plug#load('lightline.vim', 'lightline-gruvbox.vim')
        \| autocmd! load_lightline
        \| let g:lightline = {}
        \| let g:lightline.colorscheme = 'gruvbox'
        \| call lightline#enable()
augroup end

Plug 'wincent/terminus', { 'on': [] }
augroup load_terminus
  autocmd!
  autocmd InsertEnter * call plug#load('terminus')
        \| autocmd! load_terminus
augroup end

Plug 'kshenoy/vim-signature', { 'on': [] }
augroup load_vim_signature
  autocmd!
  autocmd BufReadPost * call plug#load('vim-signature')
        \|autocmd! load_vim_signature
augroup end

Plug 'inside/vim-search-pulse', { 'on': [] }
augroup load_vim_search_pulse
  autocmd!
  autocmd BufReadPost * call plug#load('vim-search-pulse')
        \| autocmd! load_vim_search_pulse
        \| let g:vim_search_pulse_mode = 'cursor_line'
        \| let g:vim_search_pulse_duration = 1000
        \| nmap n n<Plug>Pulse
        \| nmap N N<Plug>Pulse
        \| nmap * *<Plug>Pulse
        \| nmap # #<Plug>Pulse
augroup end

" EDITOR
Plug 'ntpeters/vim-better-whitespace', { 'on': [] }
augroup load_vim_better_whitespace
  autocmd!
  autocmd BufReadPost * call plug#load('vim-better-whitespace')
        \| autocmd! load_vim_better_whitespace
augroup end

Plug 'itchyny/vim-cursorword', { 'on': [] }
augroup load_vim_cursorword
  autocmd!
  autocmd BufReadPost * call plug#load('vim-cursorword')
        \| autocmd! load_vim_cursorword
        \| let g:cursorword_delay = 1000
        \| highlight CursorWord ctermbg=239
augroup end

Plug 'wellle/context.vim', { 'on': [] }
augroup load_context_vim
  autocmd!
  autocmd BufReadPost * call plug#load('context.vim')
        \| autocmd! load_context_vim
        \| let g:context_max_height = 1
        \| let g:context_max_per_indent = 1
        \| let g:context_max_join_parts = 1
augroup end

Plug 'andymass/vim-matchup', { 'on': [] }
augroup load_vim_matchup
  autocmd!
  autocmd BufReadPost * call plug#load('vim-matchup')
        \| autocmd! load_vim_matchup
augroup end

Plug 'ap/vim-css-color', { 'on': [] }
augroup load_vim_css_color
  autocmd!
  autocmd BufReadPost * call plug#load('vim-css-color')
        \| autocmd! load_vim_css_color
augroup end

Plug 'machakann/vim-highlightedyank', { 'on': [] }
augroup load_vim_highlightedyank
  autocmd!
  autocmd BufReadPost * call plug#load('vim-highlightedyank')
        \| autocmd! load_vim_highlightedyank
        \| let g:highlightedyank_highlight_duration = 1500
augroup end

Plug 'tpope/vim-commentary', { 'on': [] }
augroup load_vim_commentary
  autocmd!
  autocmd BufReadPost * call plug#load('vim-commentary')
        \| autocmd! load_vim_commentary
augroup end

Plug 'tpope/vim-surround', { 'on': [] }
augroup load_vim_surround
  autocmd!
  autocmd BufReadPost * call plug#load('vim-surround')
        \| autocmd! load_vim_surround
augroup end

Plug 'romainl/vim-cool', { 'on': [] }
augroup load_vim_cool
  autocmd!
  autocmd BufReadPost * call plug#load('vim-cool')
        \| autocmd! load_vim_cool
        \| let g:cool_total_matches = 1
augroup end

Plug 'airblade/vim-gitgutter', { 'on': [] }
augroup load_vim_gitgutter
  autocmd!
  autocmd BufReadPost * call plug#load('vim-gitgutter')
        \| autocmd! load_vim_gitgutter
        \| let g:gitgutter_map_keys = 0
augroup end

Plug 'kana/vim-textobj-user', { 'on': [] }
Plug 'glts/vim-textobj-comment', { 'on': [] }
Plug 'kana/vim-textobj-function', { 'on': [] }
Plug 'kana/vim-textobj-indent', { 'on': [] }
Plug 'wellle/targets.vim', { 'on': [] }
augroup load_vim_textobj
  autocmd!
  autocmd BufReadPost * call plug#load('vim-textobj-user', 'vim-textobj-comment', 'vim-textobj-function', 'vim-textobj-indent', 'targets.vim')
        \| autocmd! load_vim_textobj
augroup end

Plug 'airblade/vim-rooter', { 'on': [] }
augroup load_vim_rooter
  autocmd!
  autocmd BufReadPost * call plug#load('vim-rooter')
        \| autocmd! load_vim_rooter
augroup end

Plug 'mg979/vim-visual-multi', { 'on': [], 'branch': 'master' }
augroup load_vim_visual_multi
  autocmd!
  autocmd BufReadPost * call plug#load('vim-visual-multi')
        \| autocmd! load_vim_visual_multi
augroup end

Plug 'justinmk/vim-sneak', { 'on': [] }
augroup load_vim_sneak
  autocmd!
  autocmd BufReadPost * call plug#load('vim-sneak')
        \| autocmd! load_vim_sneak
augroup end

Plug 'rhysd/clever-f.vim', { 'on': [] }
augroup load_clever_f_vim
  autocmd!
  autocmd BufReadPost * call plug#load('clever-f.vim')
        \| autocmd! load_clever_f_vim
augroup end

Plug 'matze/vim-move', { 'on': ['<Plug>MoveLineDown', '<Plug>MoveLineUp', '<Plug>MoveCharLeft', '<Plug>MoveCharRight', '<Plug>MoveBlockDown', '<Plug>MoveBlockUp', '<Plug>MoveBlockLeft', '<Plug>MoveBlockRight'] }
let g:move_map_keys = 0
nmap <ESC><DOWN> <Plug>MoveLineDown
nmap <ESC><UP> <Plug>MoveLineUp
nmap <ESC><LEFT> <Plug>MoveCharLeft
nmap <ESC><RIGHT> <Plug>MoveCharRight
vmap <ESC><DOWN> <Plug>MoveBlockDown
vmap <ESC><UP> <Plug>MoveBlockUp
vmap <ESC><LEFT> <Plug>MoveBlockLeft
vmap <ESC><RIGHT> <Plug>MoveBlockRight

Plug 'preservim/nerdtree', { 'on': ['NERDTreeToggle'] }
Plug 'liuchengxu/nerdtree-dash', { 'on': ['NERDTreeToggle'] }
Plug 'tiagofumo/vim-nerdtree-syntax-highlight', { 'on': ['NERDTreeToggle'] }
Plug 'Xuyuanp/nerdtree-git-plugin', { 'on': ['NERDTreeToggle'] }
Plug 'jistr/vim-nerdtree-tabs', { 'on': ['NERDTreeToggle', 'NERDTreeTabsToggle'] }
let g:NERDTreeShowHidden = 1
let g:NERDTreeWinSize = 23
nnoremap <Leader>tn :NERDTreeToggle<CR>

Plug 'easymotion/vim-easymotion', { 'on': ['<Plug>(easymotion-overwin-line)', '<Plug>(easymotion-overwin-w)'] }
let g:EasyMotion_do_mapping = 0
nmap <Leader>gl <Plug>(easymotion-overwin-line)
nmap <Leader>gw <Plug>(easymotion-overwin-w)

Plug 'junegunn/fzf', {'do': { -> fzf#install() }, 'on': ['Files', 'Buffers', 'Colors', 'Lines', 'BLines', 'History', 'Commands', 'Rg'] }
Plug 'junegunn/fzf.vim',{ 'on': ['Files', 'Buffers', 'Colors', 'Lines', 'BLines', 'History', 'Commands', 'Rg'] }
nnoremap <Leader>ff :Files<CR>
nnoremap <C-x><C-f> :Files<CR>
nnoremap <Leader>fF :Files ~/<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <C-x><C-b> :Buffers<CR>
nnoremap <Leader>fw :Rg<CR>
nnoremap <C-x><C-w> :Rg<CR>
nnoremap <Leader>fs :BLines<CR>
nnoremap <C-s> :BLines<CR>
nnoremap <Leader>fr :History<CR>
nnoremap <C-x><C-r> :History<CR>
nnoremap <Leader>fc :Colors<CR>
nnoremap <Leader><Leader> :Commands<CR>

Plug 'junegunn/goyo.vim',{ 'on': ['Goyo'] }
Plug 'junegunn/limelight.vim', { 'on': ['Limelight'] }
nnoremap <Leader>tg :Goyo<CR>
augroup goyo_enter
  let g:limelight_conceal_ctermfg = 240
  autocmd! User GoyoEnter Limelight
augroup end
augroup goyo_leave
  autocmd! User GoyoLeave Limelight!
augroup end

Plug 't9md/vim-choosewin', { 'on': ['<Plug>(choosewin)'] }
nnoremap <C-x>o <Plug>(choosewin)
nnoremap <Leader>wo <Plug>(choosewin)

Plug 'terryma/vim-expand-region', { 'on': [] }
augroup load_expand_region_vim
  autocmd!
  autocmd BufReadPost * call plug#load('vim-expand-region')
        \| autocmd! load_expand_region_vim
augroup end

Plug 'ludovicchabant/vim-gutentags', { 'on': [], 'for': ['c', 'cpp', 'java', 'rust'] }
augroup load_vim_gutentags
  autocmd!
  autocmd BufReadPost * call plug#load('vim-gutentags')
        \| autocmd! load_vim_gutentags
augroup end

Plug 'thinca/vim-quickrun', { 'on': ['QuickRun'] }
nnoremap <Leader>tr :QuickRun<CR>

Plug 'liuchengxu/vista.vim', { 'on': ['Vista'] }
nnoremap <Leader>tv :Vista<CR>

Plug 'mbbill/undotree', { 'on': ['UndotreeToggle'] }
nnoremap <Leader>tu :UndotreeToggle<CR>

Plug 'dstein64/vim-startuptime', { 'on': ['StartupTime'] }
nnoremap <Leader>tt :StartupTime<CR>

Plug 'dyng/ctrlsf.vim', { 'on': ['CtrlSF'] }
Plug 'tpope/vim-fugitive', { 'on': ['G', 'Git'] }
Plug 'ctrlpvim/ctrlp.vim', { 'on': ['CtrlPBuffer', 'CtrlPBuffer', 'CtrlPMRU'] }
Plug 'lambdalisue/vim-suda', { 'on': ['SudaRead', 'SudaWrite'] }
Plug 'voldikss/vim-floaterm', { 'on': ['FloatermNew', 'FloatermPrev', 'FloatermNext', 'FloatermToggle', 'FloatermShow'] }
Plug 'mtth/scratch.vim', { 'on': ['Scratch'] }
Plug 'metakirby5/codi.vim', { 'on': ['Codi', 'CodiNew', 'CodiSelect', 'CodiExpand'] }
Plug 'skywind3000/asyncrun.vim', { 'on': ['AsyncRun'] }
Plug 'preservim/tagbar', { 'on': ['TagbarToggle'] }

Plug 'dense-analysis/ale', { 'on': [] }
augroup load_ale
  autocmd!
  autocmd InsertEnter * call plug#load('ale')
        \| autocmd! load_ale
        \| let g:ale_lint_on_text_changed = 0
        \| let g:ale_lint_on_save = 1
        \| let g:ale_completion_delay = 500
        \| let g:ale_echo_delay = 20
        \| let g:ale_lint_delay = 500
        \| let g:ale_echo_msg_format = '[%linter%] %code: %%s'
        \| let g:ale_lint_on_text_changed = 'normal'
        \| let g:ale_lint_on_insert_leave = 1
        \| let g:ale_command_wrapper = 'nice -n5'
        \| let g:ale_sign_error = '•'
        \| let g:ale_sign_warning = '•'
        \| let g:ale_echo_msg_error_str = '✹ Error'
        \| let g:ale_echo_msg_warning_str = '⚠ Warning'
augroup end

Plug 'sheerun/vim-polyglot', { 'on': [] }
augroup load_vim_polyglot
  autocmd!
  autocmd BufReadPost * call plug#load('vim-polyglot')
        \|autocmd! load_vim_polyglot
augroup end

Plug 'prabirshrestha/asyncomplete.vim', { 'on': [] }
Plug 'prabirshrestha/asyncomplete-buffer.vim', { 'on': [] }
Plug 'prabirshrestha/asyncomplete-file.vim', { 'on': [] }
Plug 'prabirshrestha/asyncomplete-lsp.vim', { 'on': [] }
Plug 'prabirshrestha/vim-lsp', { 'on': [] }
Plug 'mattn/vim-lsp-settings', { 'on': ['LspInstallServer', 'LspManageServers'] }
Plug 'hrsh7th/vim-vsnip', { 'on': [] }
Plug 'hrsh7th/vim-vsnip-integ', { 'on': [] }
augroup load_completion_lsp_snippet
  autocmd!
  autocmd InsertEnter * call plug#load('asyncomplete.vim', 'asyncomplete-buffer.vim', 'asyncomplete-file.vim', 'asyncomplete-lsp.vim', 'vim-lsp', 'vim-vsnip', 'vim-vsnip-integ')
        \| autocmd! load_completion_lsp_snippet
        \| let g:lsp_diagnostics_enabled = 0
        \| let g:lsp_use_native_client = 1
        \| call asyncomplete#enable_for_buffer()
        \| imap <EXPR><TAB> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : pumvisible() ? "\<C-n>" : "\<TAB>"
        \| smap <EXPR><TAB> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : pumvisible() ? "\<C-n>" : "\<TAB>"
        \| imap <EXPR><S-TAB> vsnip#available(1) ? '<Plug>(vsnip-jump-prev)' : pumvisible() ? "\<C-p>" : "\<S-TAB>"
        \| smap <EXPR><S-TAB> vsnip#available(1) ? '<Plug>(vsnip-jump-prev)' : pumvisible() ? "\<C-p>" : "\<S-TAB>"
        \| call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({ 'name': 'buffer', 'allowlist': ['*'], 'blocklist': ['go'], 'completor': function('asyncomplete#sources#buffer#completor'), 'config': { 'max_buffer_size': 10000 } }))
        \| call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({ 'name': 'file', 'allowlist': ['*'], 'priority': 10, 'completor': function('asyncomplete#sources#file#completor') }))
        \| call lsp#enable()
        \| if executable('clangd')
        \| call lsp#register_server({ 'name': 'clangd', 'cmd': { server_info -> ['clangd', '-j=12', '--enable-config', '--background-index', '--clang-tidy', '--all-scopes-completion', '--completion-style=detailed', '--header-insertion-decorators', '--limit-references=3000', '--limit-results=350'] }, 'whitelist': ['c', 'cpp'] })
        \| endif
        \| if executable('basedpyright')
        \| call lsp#register_server({ 'name': 'basedpyright', 'cmd': { server_info -> ['basedpyright-langserver', '--stdio'] }, 'whitelist': ['python'] })
        \| endif
        \| if executable('typescript-language-server')
        \| call lsp#register_server({ 'name': 'typescript-language-server', 'cmd': { server_info -> [&shell, &shellcmdflag, 'typescript-language-server --stdio'] }, 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))}, 'whitelist': ['javascript', 'javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact'] })
        \| endif
        \| if executable('gopls')
        \| call lsp#register_server({ 'name': 'gopls', 'cmd': { server_info -> ['gopls', '-remote=auto'] }, 'allowlist': ['go', 'gomod', 'gohtmltmpl', 'gotexttmpl'] })
        \| endif
augroup end
function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc')
    setlocal tagfunc=lsp#tagfunc
  endif
  nmap <BUFFER>gd <Plug>(lsp-definition)
  nmap <BUFFER>gs <Plug>(lsp-document-symbol-search)
  nmap <BUFFER>gS <Plug>(lsp-workspace-symbol-search)
  nmap <BUFFER>gr <Plug>(lsp-references)
  nmap <BUFFER>gi <Plug>(lsp-implementation)
  nmap <BUFFER>gt <Plug>(lsp-type-definition)
  nmap <BUFFER><Leader>rn <Plug>(lsp-rename)
  nmap <BUFFER>[g <Plug>(lsp-previous-diagnostic)
  nmap <BUFFER>]g <Plug>(lsp-next-diagnostic)
  nmap <BUFFER>K <Plug>(lsp-hover)
  nnoremap <BUFFER><EXPR><C-f> lsp#scroll(+4)
  nnoremap <BUFFER><EXPR><C-d> lsp#scroll(-4)
  let g:lsp_format_sync_timeout = 1000
  augroup use_lsp_document_format_sync
    autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
  augroup END
endfunction
augroup lsp_install
  autocmd!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup end

Plug 'LunarWatcher/auto-pairs', { 'on': [] }
augroup load_autopairs
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs')
        \| autocmd! load_autopairs
        \| call autopairs#AutoPairsTryInit()
augroup end

Plug 'luochen1990/rainbow', { 'on': [] }
augroup load_rainbow
  autocmd!
  autocmd InsertEnter * call plug#load('rainbow')
        \| autocmd! load_rainbow
        \| RainbowToggleOn
augroup end

Plug 'mattn/emmet-vim', { 'on': [], 'for': 'html' }
augroup load_emmet_vim
  autocmd!
  autocmd BufReadPost * call plug#load('emmet-vim')
        \| autocmd! load_emmet_vim
augroup end

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug'] }
Plug 'tpope/vim-dadbod', { 'on': ['DB'] }
Plug 'kristijanhusak/vim-dadbod-ui', { 'on': ['DBUI', 'DBUIToggle', 'DBUIAddConnection', 'DBUIFindBuffer'], 'for': 'sql' }
Plug 'kristijanhusak/vim-dadbod-completion', { 'on': ['DBUI', 'DBUIToggle', 'DBUIAddConnection', 'DBUIFindBuffer'], 'for': 'sql' }
Plug 'vim-test/vim-test', { 'on': ['TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit'] }

if has('python3')
  Plug 'puremourning/vimspector', { 'on': ['VimspectorInstall', '<Plug>VimspectorContinue', '<Plug>VimspectorBreakpoints', '<Plug>VimspectorToggleBreakpoint', '<Plug>VimspectorGoToCurrentLine'] }
  Plug 'vim-autoformat/vim-autoformat', { 'on': ['Autoformat'] }
endif

Plug 'liuchengxu/vim-which-key', { 'on': ['WhichKey', 'WhichKey!'] }
nnoremap <silent> <Leader> :<C-u>WhichKey '<Space>'<CR>
nnoremap <silent> <Localleader> :<C-u>WhichKey ','<CR>
augroup load_vim_which_key
  let g:which_key_map = {}
  let g:which_key_map['c'] = {
        \ 'name': '+Config',
        \ 'e': ['<Leader>ce', 'Edit'],
        \ 'r': ['<Leader>cr', 'Reload'],
        \ }
  let g:which_key_map['w'] = {
        \ 'name': '+Window',
        \ 'o': ['<Leader>wo', '<Plug>choosewin'],
        \ }
  let g:which_key_map['f'] = {
        \ 'name': '+Find',
        \ 'b': ['<Leader>fb', 'Buffers'],
        \ 'c': ['<Leader>fc', 'Colorschemes'],
        \ 'f': ['<Leader>ff', 'Files'],
        \ 'F': ['<Leader>ff', 'Files in root'],
        \ 's': ['<Leader>fs', 'Buffer Words'],
        \ 'w': ['<Leader>fw', 'Words'],
        \ 'r': ['<Leader>fr', 'Recent Files'],
        \ }
  let g:which_key_map['t'] = {
        \ 'name': '+Toggle',
        \ 'g': ['<Leader>tg', 'Goyo'],
        \ 'r': ['<Leader>tr', 'Run Code'],
        \ 'v': ['<Leader>tv', 'Code Outline'],
        \ 'u': ['<Leader>tu', 'Undo Tree'],
        \ 't': ['<Leader>tt', 'Startup Time'],
        \ }
  autocmd! User vim-which-key call which_key#register('<Space>', 'g:which_key_map', 'n')
augroup end

call plug#end()
