"use strict";

module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 13,
    fontFamily: '"JetBrainsMono Nerd Font"',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0.4,
    cursorColor: "#f5e0dc",
    cursorAccentColor: "#11111b",
    cursorShape: "BLOCK",
    cursorBlink: true,
    foregroundColor: "#cdd6f4",
    backgroundColor: "#11111b",
    selectionColor: "#9399b2",
    borderColor: "#1e1e2e",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "8px 8px",
    colors: {
      black: "#11111b",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#cba6f7",
      cyan: "#89dceb",
      white: "#cdd6f4",
      lightBlack: "#1e1e2e",
      lightRed: "#f38ba8",
      lightGreen: "#a6e3a1",
      lightYellow: "#f9e2af",
      lightBlue: "#89b4fa",
      lightMagenta: "#cba6f7",
      lightCyan: "#89dceb",
      lightWhite: "#cdd6f4",
      limeGreen: "#94e2d5",
      lightCoral: "#eba0ac",
    },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: false,
    disableAutoUpdates: true,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {},
};
